project:
  type: website
  
execute:
  freeze: auto

website:
  title: "Cours introduction au webscrapping"

  page-footer:
    right: "Ce site a été créé avec [Quarto](https://quarto.org/)"
    
  sidebar:
    pinned: true
    align: center
    style: "docked"
    contents:
      - href: 1_intro.qmd
        text: Introduction au webscrapping
      - href: 2_juridique.qmd
        text: Le webscrapping et le juridique
      - href: 3_html.qmd
        text: Internet et le web
      - href: 4_premier_pas.qmd
        text: Premiers pas avec BeautifulSoup
      - href: 5_api.qmd
        text: Requêter une api
      - href: 6_site_dynamique.qmd
        text: Webscrapping avec simulation dynamique
        
format:
  html:
    theme:
      light: flatly
      dark: darkly
    code-copy: true
    code-overflow: wrap
    toc: true
